/**
 * Client
 * Import from \"ayfuneus\" Function App
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class LoginWithCustomIDResponseDataUser {
  
  @SerializedName("Id")
  private String id = null;
  @SerializedName("DisplayId")
  private String displayId = null;
  @SerializedName("DisplayName")
  private String displayName = null;
  @SerializedName("CreatedAt")
  private String createdAt = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getDisplayId() {
    return displayId;
  }
  public void setDisplayId(String displayId) {
    this.displayId = displayId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getDisplayName() {
    return displayName;
  }
  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCreatedAt() {
    return createdAt;
  }
  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LoginWithCustomIDResponseDataUser loginWithCustomIDResponseDataUser = (LoginWithCustomIDResponseDataUser) o;
    return (this.id == null ? loginWithCustomIDResponseDataUser.id == null : this.id.equals(loginWithCustomIDResponseDataUser.id)) &&
        (this.displayId == null ? loginWithCustomIDResponseDataUser.displayId == null : this.displayId.equals(loginWithCustomIDResponseDataUser.displayId)) &&
        (this.displayName == null ? loginWithCustomIDResponseDataUser.displayName == null : this.displayName.equals(loginWithCustomIDResponseDataUser.displayName)) &&
        (this.createdAt == null ? loginWithCustomIDResponseDataUser.createdAt == null : this.createdAt.equals(loginWithCustomIDResponseDataUser.createdAt));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.displayId == null ? 0: this.displayId.hashCode());
    result = 31 * result + (this.displayName == null ? 0: this.displayName.hashCode());
    result = 31 * result + (this.createdAt == null ? 0: this.createdAt.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class LoginWithCustomIDResponseDataUser {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  displayId: ").append(displayId).append("\n");
    sb.append("  displayName: ").append(displayName).append("\n");
    sb.append("  createdAt: ").append(createdAt).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
