/**
 * Client
 * Import from \"ayfuneus\" Function App
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class LoginWithCustomIDResponseDataLinkedAccountsInner {
  
  @SerializedName("Platform")
  private String platform = null;
  @SerializedName("PlatformUserId")
  private String platformUserId = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getPlatform() {
    return platform;
  }
  public void setPlatform(String platform) {
    this.platform = platform;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getPlatformUserId() {
    return platformUserId;
  }
  public void setPlatformUserId(String platformUserId) {
    this.platformUserId = platformUserId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LoginWithCustomIDResponseDataLinkedAccountsInner loginWithCustomIDResponseDataLinkedAccountsInner = (LoginWithCustomIDResponseDataLinkedAccountsInner) o;
    return (this.platform == null ? loginWithCustomIDResponseDataLinkedAccountsInner.platform == null : this.platform.equals(loginWithCustomIDResponseDataLinkedAccountsInner.platform)) &&
        (this.platformUserId == null ? loginWithCustomIDResponseDataLinkedAccountsInner.platformUserId == null : this.platformUserId.equals(loginWithCustomIDResponseDataLinkedAccountsInner.platformUserId));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.platform == null ? 0: this.platform.hashCode());
    result = 31 * result + (this.platformUserId == null ? 0: this.platformUserId.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class LoginWithCustomIDResponseDataLinkedAccountsInner {\n");
    
    sb.append("  platform: ").append(platform).append("\n");
    sb.append("  platformUserId: ").append(platformUserId).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
