/**
 * Client
 * Import from \"ayfuneus\" Function App
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import org.openapitools.client.model.LoginWithCustomIDResponseDataLinkedAccountsInner;
import org.openapitools.client.model.LoginWithCustomIDResponseDataUser;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class LoginWithCustomIDResponseData {
  
  @SerializedName("AccessToken")
  private String accessToken = null;
  @SerializedName("User")
  private LoginWithCustomIDResponseDataUser user = null;
  @SerializedName("LinkedAccounts")
  private List<LoginWithCustomIDResponseDataLinkedAccountsInner> linkedAccounts = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getAccessToken() {
    return accessToken;
  }
  public void setAccessToken(String accessToken) {
    this.accessToken = accessToken;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public LoginWithCustomIDResponseDataUser getUser() {
    return user;
  }
  public void setUser(LoginWithCustomIDResponseDataUser user) {
    this.user = user;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<LoginWithCustomIDResponseDataLinkedAccountsInner> getLinkedAccounts() {
    return linkedAccounts;
  }
  public void setLinkedAccounts(List<LoginWithCustomIDResponseDataLinkedAccountsInner> linkedAccounts) {
    this.linkedAccounts = linkedAccounts;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LoginWithCustomIDResponseData loginWithCustomIDResponseData = (LoginWithCustomIDResponseData) o;
    return (this.accessToken == null ? loginWithCustomIDResponseData.accessToken == null : this.accessToken.equals(loginWithCustomIDResponseData.accessToken)) &&
        (this.user == null ? loginWithCustomIDResponseData.user == null : this.user.equals(loginWithCustomIDResponseData.user)) &&
        (this.linkedAccounts == null ? loginWithCustomIDResponseData.linkedAccounts == null : this.linkedAccounts.equals(loginWithCustomIDResponseData.linkedAccounts));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.accessToken == null ? 0: this.accessToken.hashCode());
    result = 31 * result + (this.user == null ? 0: this.user.hashCode());
    result = 31 * result + (this.linkedAccounts == null ? 0: this.linkedAccounts.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class LoginWithCustomIDResponseData {\n");
    
    sb.append("  accessToken: ").append(accessToken).append("\n");
    sb.append("  user: ").append(user).append("\n");
    sb.append("  linkedAccounts: ").append(linkedAccounts).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
