/**
 * Client
 * Import from \"ayfuneus\" Function App
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class LoginwithCustomID {
  
  @SerializedName("CustomId")
  private String customId = null;
  @SerializedName("Token")
  private String token = null;
  @SerializedName("CreateAccount")
  private Boolean createAccount = null;
  @SerializedName("ProjectID")
  private String projectID = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCustomId() {
    return customId;
  }
  public void setCustomId(String customId) {
    this.customId = customId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getToken() {
    return token;
  }
  public void setToken(String token) {
    this.token = token;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getCreateAccount() {
    return createAccount;
  }
  public void setCreateAccount(Boolean createAccount) {
    this.createAccount = createAccount;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getProjectID() {
    return projectID;
  }
  public void setProjectID(String projectID) {
    this.projectID = projectID;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LoginwithCustomID loginwithCustomID = (LoginwithCustomID) o;
    return (this.customId == null ? loginwithCustomID.customId == null : this.customId.equals(loginwithCustomID.customId)) &&
        (this.token == null ? loginwithCustomID.token == null : this.token.equals(loginwithCustomID.token)) &&
        (this.createAccount == null ? loginwithCustomID.createAccount == null : this.createAccount.equals(loginwithCustomID.createAccount)) &&
        (this.projectID == null ? loginwithCustomID.projectID == null : this.projectID.equals(loginwithCustomID.projectID));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.customId == null ? 0: this.customId.hashCode());
    result = 31 * result + (this.token == null ? 0: this.token.hashCode());
    result = 31 * result + (this.createAccount == null ? 0: this.createAccount.hashCode());
    result = 31 * result + (this.projectID == null ? 0: this.projectID.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class LoginwithCustomID {\n");
    
    sb.append("  customId: ").append(customId).append("\n");
    sb.append("  token: ").append(token).append("\n");
    sb.append("  createAccount: ").append(createAccount).append("\n");
    sb.append("  projectID: ").append(projectID).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
