/**
 * Client
 * Import from \"ayfuneus\" Function App
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonParseException;
import com.google.gson.reflect.TypeToken;
import java.lang.reflect.Type;
import java.util.List;
import java.util.Date;
import org.openapitools.client.model.*;

public class JsonUtil {
  public static GsonBuilder gsonBuilder;

  static {
    gsonBuilder = new GsonBuilder();
    gsonBuilder.serializeNulls();
    gsonBuilder.setDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ");
    gsonBuilder.registerTypeAdapter(Date.class, new JsonDeserializer<Date>() {
      public Date deserialize(JsonElement json, Type typeOfT, JsonDeserializationContext context) throws JsonParseException {
        return new Date(json.getAsJsonPrimitive().getAsLong());
      }
    });
  }

  public static Gson getGson() {
    return gsonBuilder.create();
  }

  public static String serialize(Object obj){
    return getGson().toJson(obj);
  }

  public static <T> T deserializeToList(String jsonString, Class cls){
    return getGson().fromJson(jsonString, getListTypeForDeserialization(cls));
  }

  public static <T> T deserializeToObject(String jsonString, Class cls){
    return getGson().fromJson(jsonString, getTypeForDeserialization(cls));
  }

  public static Type getListTypeForDeserialization(Class cls) {
    String className = cls.getSimpleName();
    
    if ("LoginWithCustomIDResponse".equalsIgnoreCase(className)) {
      return new TypeToken<List<LoginWithCustomIDResponse>>(){}.getType();
    }
    
    if ("LoginWithCustomIDResponseData".equalsIgnoreCase(className)) {
      return new TypeToken<List<LoginWithCustomIDResponseData>>(){}.getType();
    }
    
    if ("LoginWithCustomIDResponseDataLinkedAccountsInner".equalsIgnoreCase(className)) {
      return new TypeToken<List<LoginWithCustomIDResponseDataLinkedAccountsInner>>(){}.getType();
    }
    
    if ("LoginWithCustomIDResponseDataUser".equalsIgnoreCase(className)) {
      return new TypeToken<List<LoginWithCustomIDResponseDataUser>>(){}.getType();
    }
    
    if ("LoginwithCustomID".equalsIgnoreCase(className)) {
      return new TypeToken<List<LoginwithCustomID>>(){}.getType();
    }
    
    if ("NotFound".equalsIgnoreCase(className)) {
      return new TypeToken<List<NotFound>>(){}.getType();
    }
    
    return new TypeToken<List<Object>>(){}.getType();
  }

  public static Type getTypeForDeserialization(Class cls) {
    String className = cls.getSimpleName();
    
    if ("LoginWithCustomIDResponse".equalsIgnoreCase(className)) {
      return new TypeToken<LoginWithCustomIDResponse>(){}.getType();
    }
    
    if ("LoginWithCustomIDResponseData".equalsIgnoreCase(className)) {
      return new TypeToken<LoginWithCustomIDResponseData>(){}.getType();
    }
    
    if ("LoginWithCustomIDResponseDataLinkedAccountsInner".equalsIgnoreCase(className)) {
      return new TypeToken<LoginWithCustomIDResponseDataLinkedAccountsInner>(){}.getType();
    }
    
    if ("LoginWithCustomIDResponseDataUser".equalsIgnoreCase(className)) {
      return new TypeToken<LoginWithCustomIDResponseDataUser>(){}.getType();
    }
    
    if ("LoginwithCustomID".equalsIgnoreCase(className)) {
      return new TypeToken<LoginwithCustomID>(){}.getType();
    }
    
    if ("NotFound".equalsIgnoreCase(className)) {
      return new TypeToken<NotFound>(){}.getType();
    }
    
    return new TypeToken<Object>(){}.getType();
  }

};
